name: Build and Deploy

on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      

      - name: Install and Build
        run: |
          npm ci
          npm run build
          touch build/.nojekyll
        working-directory: ./site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site/build # The folder the action should deploy.
